added back jacoco tests

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -40,6 +40,26 @@ jobs:
       - name: Verify Java Installation
         run: java -version
 
+      - name: Build and run tests with JaCoCo
+        run: |
+          mvn clean test
+          mvn jacoco:report
+
+      - name: Check JaCoCo Coverage Threshold
+        run: |
+          COVERAGE=$(grep -oPm1 "(?<=<counter type=\"LINE\" missed=\")\d+" target/site/jacoco/jacoco.xml)
+          if [ "$COVERAGE" -lt "80" ]; then
+            echo "Code coverage is below 80%, build failed."
+            exit 1
+          fi
+        shell: bash
+      - name: Debug AWS Credentials
+        run: |
+          echo "AWS_REGION=${{ secrets.AWS_REGION }}"
+          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
+          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
+          echo "ECR_REPO_URI=${{ secrets.ECR_REPO_URI }}"
+
       - name: Build, Test, and Analyze with Maven
         run: |
           mvn clean verify sonar:sonar \
