update to build docker first
# Conflicts:
#	.github/workflows/docker-build.yml

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -35,14 +35,49 @@ jobs:
         uses: actions/setup-java@v2
         with:
           java-version: '21'
-          distribution: 'temurin' 
+          distribution: 'temurin'
 
-      # **Updated Step**: Use SonarCloud GitHub Action for SAST and Linting
+      # Build and run tests with JaCoCo
+      - name: Build and run tests with JaCoCo
+        run: |
+          mvn clean test
+          mvn jacoco:report
+
+      - name: Check JaCoCo Coverage Threshold
+        run: |
+          COVERAGE=$(grep -oPm1 "(?<=<counter type=\"LINE\" missed=\")\d+" target/site/jacoco/jacoco.xml)
+          if [ "$COVERAGE" -lt "80" ]; then
+            echo "Code coverage is below 80%, build failed."
+            exit 1
+          fi
+        shell: bash
+
+      - name: Debug AWS Credentials
+        run: |
+          echo "AWS_REGION=${{ secrets.AWS_REGION }}"
+          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
+          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
+          echo "ECR_REPO_URI=${{ secrets.ECR_REPO_URI }}"
+
+      - name: Log in to Amazon ECR Public
+        run: |
+          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l0d0i0v3
+
+      - name: Build Docker image
+        run: |
+          docker build -t shopsmartsg/profile-service .
+          docker tag shopsmartsg/profile-service:latest ${{ secrets.ECR_REPO_URI }}:latest
+
+      - name: Push Docker image to ECR
+        run: |
+          docker push ${{ secrets.ECR_REPO_URI }}:latest
+
+      # **Moved Step**: Use SonarCloud GitHub Action for SAST and Linting
       - name: SonarCloud Scan with Linting
         uses: sonarsource/sonarcloud-github-action@v1.5
         env:
           JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.4-7/x64
-          PATH: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.4-7/x64/bin:${{ env.PATH }} 
+          PATH: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.4-7/x64/bin:${{ env.PATH }}
         with:
           entryPoint: sonar-scanner
           args: >
